### ISSUE TITLE
Support variable number of arguments in pattern matching subproc calls

### ISSUE THREAD

**Issue by gilbo** [ChezJrk/SYS_ATL#19]
For instance, `f(_,_,_)` shouldn't have to match the number of arguments explicitly; we should just be able to write `f(_)` and that can pattern match against `f(2,x,z)` without problem

**Comment by alexreinking** [comment]
Is this still relevant? @yamaguchi1024 said this was implemented in our meeting today.

**Comment by yamaguchi1024** [comment]
Yep this works
